---
- hosts: 10.0.0.5
  become: yes
  tasks:
  -  include_tasks: myfile.yml
  -  name: copy file from master to nodes\
     copy:
        src: mycopyfile
        dest: /home/sree/mycopyfile
  -  name: install webserver
     apt:
       name: apache2
       state: present      
